apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      hostNetwork: true
      containers:
        - name: tomcat-app
          image: theparasuraman/vod-docker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              hostPort: 9092        # ‚Üê different port on host
