apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      hostNetwork: true   # equivalent to --network host
      containers:
        - name: tomcat-app
          image: my-tomcat-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: host-home
              mountPath: /home/user
      volumes:
        - name: host-home
          hostPath:
            path: /home/user
            type: Directory
